# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Login:
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(653, 478)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.password = QtWidgets.QLabel(Login)
        self.password.setMinimumSize(QtCore.QSize(60, 30))
        self.password.setMaximumSize(QtCore.QSize(60, 30))
        self.password.setObjectName("password")
        self.horizontalLayout_4.addWidget(self.password)
        self.l_password = QtWidgets.QLineEdit(Login)
        self.l_password.setMinimumSize(QtCore.QSize(300, 30))
        self.l_password.setMaximumSize(QtCore.QSize(300, 30))
        self.l_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.l_password.setObjectName("l_password")
        self.horizontalLayout_4.addWidget(self.l_password)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login = QtWidgets.QLabel(Login)
        self.login.setMinimumSize(QtCore.QSize(60, 30))
        self.login.setMaximumSize(QtCore.QSize(60, 30))
        self.login.setObjectName("login")
        self.horizontalLayout_3.addWidget(self.login)
        self.l_login = QtWidgets.QLineEdit(Login)
        self.l_login.setMinimumSize(QtCore.QSize(300, 30))
        self.l_login.setMaximumSize(QtCore.QSize(300, 30))
        self.l_login.setObjectName("l_login")
        self.horizontalLayout_3.addWidget(self.l_login)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(200, 0, 100, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Back_btn = QtWidgets.QPushButton(Login)
        self.Back_btn.setObjectName("Back_btn")
        self.horizontalLayout.addWidget(self.Back_btn)
        self.Login_btn = QtWidgets.QPushButton(Login)
        self.Login_btn.setDefault(True)
        self.Login_btn.setFlat(False)
        self.Login_btn.setObjectName("Login_btn")
        self.horizontalLayout.addWidget(self.Login_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.password.setText(_translate("Login", "Password"))
        self.login.setText(_translate("Login", "Login"))
        self.Back_btn.setText(_translate("Login", "Back"))
        self.Login_btn.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
