# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


btn_style = """QPushButton {
                    border: 1px solid gray;
                    font: bold 15pt \"Segoe Print\";
                    border-radius: 15px;
                    background-color: qlineargradient(x1: 0.5, y1: 0.5, x2: 1, y2: 1,
                                                      stop: 0 #dadbde, stop: 1 #f6f7fa);
                }
                QPushButton:hover {
                    border: 1px solid gray;
                    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                                                      stop: 0 #f6f7fa, stop: 1 #dadbde);
                }
                QPushButton:pressed {
                    border: 1px solid gray;
                    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                                                      stop: 0 #dadbde, stop: 1 #f6f7fa);
                }"""


class Ui_WelcomeFrame:
    def setupUi(self, WelcomeFrame):
        WelcomeFrame.setObjectName("WelcomeFrame")
        WelcomeFrame.setWindowTitle("WelcomeFrame")
        WelcomeFrame.setFixedSize(653, 478)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WelcomeFrame.sizePolicy().hasHeightForWidth())
        WelcomeFrame.setSizePolicy(sizePolicy)
        WelcomeFrame.setUnifiedTitleAndToolBarOnMac(False)
        self.canvas = QtWidgets.QWidget(WelcomeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setObjectName("canvas")
        self.gridLayout = QtWidgets.QGridLayout(self.canvas)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_text = QtWidgets.QLabel(self.canvas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_text.sizePolicy().hasHeightForWidth())
        self.title_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(60)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.title_text.setFont(font)
        self.title_text.setTabletTracking(True)
        self.title_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.title_text.setObjectName("title_text")
        self.verticalLayout.addWidget(self.title_text)
        self.btn_layout = QtWidgets.QVBoxLayout()
        self.btn_layout.setContentsMargins(150, 100, 150, 50)
        self.btn_layout.setObjectName("btn_layout")
        self.login_btn = QtWidgets.QPushButton(self.canvas)
        self.login_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setObjectName("login_btn")
        self.login_btn.setMinimumSize(300, 30)
        self.login_btn.setMaximumSize(600, 60)
        self.login_btn.setStyleSheet(btn_style)
        self.btn_layout.addWidget(self.login_btn)
        self.signup_btn = QtWidgets.QPushButton(self.canvas)
        self.signup_btn.setEnabled(True)
        self.signup_btn.setMinimumSize(300, 30)
        self.signup_btn.setMaximumSize(600, 60)
        self.signup_btn.setStyleSheet(btn_style)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signup_btn.sizePolicy().hasHeightForWidth())
        self.signup_btn.setSizePolicy(sizePolicy)
        self.signup_btn.setBaseSize(QtCore.QSize(100, 10))
        self.signup_btn.setObjectName("signup_btn")
        self.btn_layout.addWidget(self.signup_btn)
        self.verticalLayout.addLayout(self.btn_layout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        WelcomeFrame.setCentralWidget(self.canvas)
        self.statusbar = QtWidgets.QStatusBar(WelcomeFrame)
        self.statusbar.setObjectName("statusbar")
        WelcomeFrame.setStatusBar(self.statusbar)

        self.retranslateUi(WelcomeFrame)
        QtCore.QMetaObject.connectSlotsByName(WelcomeFrame)

    def retranslateUi(self, WelcomeFrame):
        _translate = QtCore.QCoreApplication.translate
        WelcomeFrame.setWindowTitle(_translate("WelcomeFrame", "WorkTimer"))
        self.title_text.setText(_translate("WelcomeFrame", "WorkTimer"))
        self.login_btn.setText(_translate("WelcomeFrame", "LOGIN"))
        self.signup_btn.setText(_translate("WelcomeFrame", "SIGN UP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomeFrame = QtWidgets.QMainWindow()
    ui = Ui_WelcomeFrame()
    ui.setupUi(WelcomeFrame)
    WelcomeFrame.show()
    sys.exit(app.exec_())
