# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugin_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


button = """QPushButton {
                border: 1px solid gray;
                border-radius: 20px;
                font: 75 20pt \"Segoe Print\";
                background-color: qlineargradient(x1: 0.5, y1: 0.5, x2: 1, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);
            }
            QPushButton:hover {
                border: 1px solid gray;
                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);
            }
            QPushButton:pressed {
                border: 1px solid gray;
                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);
            }"""


class Ui_TestPlugin:
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(653, 478)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(100, 100, 100, 100)
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.test_label.setFont(font)
        self.test_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.test_label.setObjectName("test_label")
        self.verticalLayout.addWidget(self.test_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Back = QtWidgets.QPushButton(Dialog)
        self.btn_Back.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_Back.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        font.setStrikeOut(False)
        self.btn_Back.setFont(font)
        self.btn_Back.setStyleSheet(button)
        self.btn_Back.setObjectName("btn_Back")
        self.horizontalLayout.addWidget(self.btn_Back)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "WorkTimer"))
        self.test_label.setText(_translate("Dialog", "This is a test plug-in \nfor basic user"))
        self.btn_Back.setText(_translate("Dialog", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_TestPlugin()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
