# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logout_prompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


btn_style = """QPushButton {
                    border: 1px solid gray;
                    border-radius: 13px;
                    font: 10pt \\\"Segoe Print\\\";
                    background-color: qlineargradient(x1: 0.5, y1: 0.5, x2: 1, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);
                }
                QPushButton:default {
                    border: 2px solid gray;
                }
                    QPushButton:hover {
                    border: 1px solid gray;
                    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);
                }
                QPushButton:pressed {
                    border: 1px solid gray;
                    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);
                }"""


class Ui_AskDialog:
    def setupUi(self, AskDialog, title, description):
        AskDialog.setObjectName("WorkTimer")
        AskDialog.setFixedSize(500, 200)
        self.gridLayout = QtWidgets.QGridLayout(AskDialog)
        self.verticalLayout = QtWidgets.QVBoxLayout()

        # main_info
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setStyleSheet("color: black; font: bold 16pt \"Segoe Print\"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setText(title)
        self.verticalLayout.addWidget(self.label_2)


        # description
        self.label = QtWidgets.QLabel()
        self.label.setStyleSheet("color: black; font: 12pt \"Segoe Print\"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setText(description)
        self.verticalLayout.addWidget(self.label)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.btn_cancel = QtWidgets.QPushButton(AskDialog)
        self.btn_cancel.setMinimumSize(QtCore.QSize(100, 26))
        self.btn_cancel.setMaximumSize(QtCore.QSize(100, 26))
        self.btn_cancel.setStyleSheet(btn_style)
        self.btn_cancel.setText("Cencel")
        self.horizontalLayout.addWidget(self.btn_cancel)

        self.btn_Ok = QtWidgets.QPushButton(AskDialog)
        self.btn_Ok.setMinimumSize(QtCore.QSize(100, 26))
        self.btn_Ok.setMaximumSize(QtCore.QSize(100, 26))
        self.btn_Ok.setStyleSheet(btn_style)
        self.btn_Ok.setText("Ok")
        self.horizontalLayout.addWidget(self.btn_Ok)

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        QtCore.QMetaObject.connectSlotsByName(AskDialog)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AskDialog = QtWidgets.QDialog()
    ui = Ui_AskDialog()
    ui.setupUi(AskDialog, "ERROR", "DESSCRIPTION")
    AskDialog.show()
    sys.exit(app.exec_())
